In [12]:
import sqlite3, pandas as pd
conn = sqlite3.connect("music4all.db")
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;", conn)
tables

                name
0          id_genres
1     id_information
2            id_lang
3        id_metadata
4            id_tags
5  listening_history

In [15]:
df = pd.read_sql("SELECT * FROM listening_history", conn)
df.head()

            user              song         timestamp
0  user_007XIjOr  DaTQ53TUmfP93FSr  2019-02-20 12:28
1  user_007XIjOr  dGeyvi5WCOjDU7da  2019-02-20 12:35
2  user_007XIjOr  qUm54NYOjeFhmKYx  2019-02-20 12:48
3  user_007XIjOr  FtnuMT1DlevSR2n5  2019-02-20 12:52
4  user_007XIjOr  LHETTZcSZLeaVOGh  2019-02-20 13:09

In [8]:
conn = sqlite3.connect("music4all_final.sqlite")
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name;", conn)
tables

          name
0     final_db
1  musical_new

In [11]:
test = pd.read_sql("SELECT * FROM final_db", conn)
test

,id,musical_db,lyrical_db,song_name,album,artist,semantic_db
0,0009fFIM1eYThaPg,"[0.07604348659515381, 0.00861547701060772, -0....","[-0.0033781668171286583, 0.011112084612250328,...",Rain on Me,3 Words,Cheryl,"[0.0978178009390831,-0.0061011482030153275,0.0..."
1,0010xmHR6UICBOYT,"[0.07058699429035187, 0.01870115101337433, -0....","[0.05815385654568672, -0.009112397208809853, 0...",After Thoughts,The Beauty in All,Oddisee,"[-0.054971594363451004,-0.03325279802083969,-0..."
2,002Jyd0vN4HyCpqL,"[0.07372468709945679, 0.016590703278779984, -0...","[-0.03389301523566246, 0.032592788338661194, 0...",ME 262,Secret Treaties,Blue Öyster Cult,"[-0.054807618260383606,0.004959520883858204,-0..."
3,006TYKNjNxWjfKjy,"[0.07935899496078491, 0.031098611652851105, -0...","[-0.05854003131389618, -0.03212481737136841, 0...",Flames of Revenge,Legendary Years (Re-Recorded),Rhapsody,"[0.03915850818157196,-0.062305912375450134,0.0..."
4,007LIJOPQ4Sb98qV,"[0.06902480125427246, 0.027448248118162155, -0...","[-0.002691638423129916, -0.018016116693615913,...",Nostalgia,What Does Anything Mean? Basically (2009 Remas...,The Chameleons,"[-0.05041821300983429,-0.10588043928146362,0.0..."
...,...,...,...,...,...,...,...
109264,zzyyPUs7hC9Nz2e1,"[0.05122791975736618, 0.03276118263602257, -0....","[0.03249511495232582, 0.010329384356737137, -0...",Vampires,Modern Ruin,Frank Carter & The Rattlesnakes,"[-0.018610823899507523,0.04963809996843338,0.0..."
109265,zzz0n04uuTUA7fNh,"[0.08093161880970001, 0.02886452153325081, -0....","[-0.028081415221095085, -0.024841494858264923,...",Heartbreaker,Journals,Justin Bieber,"[0.004074763040989637,-0.028319930657744408,-0..."
109266,zzzj3LYaZtYtbzSr,"[0.07240122556686401, 0.024198895320296288, -0...","[-0.007332625333219767, 0.0028875891584903, -0...",Après Moi - Live In London,Live In London,Regina Spektor,"[0.013253732584416866,0.07186240702867508,0.07..."
109267,zzznMjZAKnJJXQSj,"[0.05921902135014534, 0.011026952415704727, -0...","[-0.0525948591530323, 0.004303360357880592, -0...",New Rules (Initial Talk Remix),New Rules (Initial Talk Remix),Dua Lipa,"[-0.008234084583818913,0.046497445553541183,-0..."
109268,zzzwh2ktIWjsR7xp,"[0.06550147384405136, 0.032227590680122375, -0...","[0.0036885032895952463, -0.008996081538498402,...",In the End,Fallen Empires,Snow Patrol,"[-0.05869755521416664,0.10847461223602295,-0.0..."